---
title: "HLTWeek8"
output: html_document
---

```{r}
## 1 Write an R program to create three vectors a, b, c with 5 integers. Combine the three vectors to become a 3×5 matrix where each column represents a vector. Print the content of the matrix. Plot a graph and label correctly

a=c(1,2,3,4,5)
b=c(6,7,8,9,10)
c=c(11,12,13,14,15)

d=cbind(a,b,c)

print(d)

matplot(d,x=a,y=b, type ="b", pch=10, col=1:3)

```
```{r}

## 2 Write a R program to create a Data frames which contain details of 5 employees and display the details.  (Name, Age, Role and Length of service)

Employees_details = data.frame(Name=c("Rania A","Rizwane U","Joud U", "Joumana U","Khalifa U"),
                      Age=c(31,35,25,26,32),
                      Role=c("Manager","CEO","Cook","WAITRESS","WAITRESS"),
                      LOS=c(3,3,3,3,2)
                      )

print(Employees_details)



```
```{r}
## 3 Import the GGPLOT 2 library and plot a graph using the qplot function.  X axis is the sequence of 1:20 and the y axis is the x^ 
##  Label the graph appropriately. install.packages("ggplot2", dependencies = TRUE)


```



```{r}
## 4 Create a simple bar plot of five subjects


hights = c(70, 95, 80, 74,110)
barplot(hights, main = "Comparing hights of five furnitures in cm",xlab = "hights",ylab = "furniture",names.arg = c("table", "chair", "lamp", "cupboard", "side-board"),col = "darkred",horiz = FALSE)


```